In [132]:
import pandas as pd
import numpy as np

# Step 2: Load datasets
Dataset = pd.read_csv("train_preprocessed.csv")

In [133]:
Dataset

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,1,0,3,22.0,1,0,7.2500,1,0,1
1,2,1,1,38.0,1,0,71.2833,0,0,0
2,3,1,3,26.0,0,0,7.9250,0,0,1
3,4,1,1,35.0,1,0,53.1000,0,0,1
4,5,0,3,35.0,0,0,8.0500,1,0,1
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,27.0,0,0,13.0000,1,0,1
887,888,1,1,19.0,0,0,30.0000,0,0,1
888,889,0,3,28.0,1,2,23.4500,0,0,1
889,890,1,1,26.0,0,0,30.0000,1,0,0
890,891,0,3,32.0,0,0,7.7500,1,1,0

In [134]:
dupdataset=pd.DataFrame()

In [135]:
dupdataset.loc['Mean', 'Age']   = Dataset['Age'].mean()
dupdataset.loc['Median', 'Age'] = Dataset['Age'].median()
dupdataset.loc['Mode', 'Age']   = Dataset['Age'].mode()[0]

print(dupdataset)

              Age
Mean    29.361582
Median  28.000000
Mode    28.000000

In [136]:
import numpy as np
np.percentile(Dataset["Age"],100)

np.float64(80.0)

In [137]:
dupdata=pd.DataFrame(index=["mean","median","mode","Q1:25%","Q2:50%","Q3:75%","99","Q4:100%","IQR","1.5rule","Lesser","Greater","Min","Max"],columns=['Age','Fare'])
for columnName in ['Age','Fare']:
        dupdata.loc["mean", columnName]   = Dataset[columnName].mean()
        dupdata.loc["median", columnName] = Dataset[columnName].median()
        dupdata.loc["mode", columnName]   = Dataset[columnName].mode()[0]
        dupdata.loc["Q1:25%", columnName] = Dataset[columnName].quantile(0.25)
        dupdata.loc["Q2:50%", columnName] = Dataset[columnName].quantile(0.50)
        dupdata.loc["Q3:75%", columnName] = Dataset[columnName].quantile(0.75)
        dupdata.loc["99", columnName]     = np.percentile(Dataset[columnName], 99)
        dupdata.loc["Q4:100%", columnName]= Dataset[columnName].max()
        dupdata.loc["IQR", columnName]    = dupdata.loc["Q3:75%", columnName] - dupdata.loc["Q1:25%", columnName]
        dupdata.loc["1.5rule", columnName]= 1.5 * dupdata.loc["IQR", columnName]
        dupdata.loc["Lesser", columnName] = dupdata.loc["Q1:25%", columnName] - dupdata.loc["1.5rule", columnName]
        dupdata.loc["Greater", columnName]= dupdata.loc["Q3:75%", columnName] + dupdata.loc["1.5rule", columnName]
        dupdata.loc["Min", columnName]    = Dataset[columnName].min()
        dupdata.loc["Max", columnName]    = Dataset[columnName].max()

In [140]:
dupdata

               Age       Fare
mean     29.361582  32.204208
median        28.0    14.4542
mode          28.0       8.05
Q1:25%        22.0     7.9104
Q2:50%        28.0    14.4542
Q3:75%        35.0       31.0
99            65.0  249.00622
Q4:100%       80.0   512.3292
IQR           13.0    23.0896
1.5rule       19.5    34.6344
Lesser         2.5    -26.724
Greater       54.5    65.6344
Min           0.42        0.0
Max           80.0   512.3292

In [141]:
#Age frequency
freqTable=pd.DataFrame(columns=["Age_unique_values","Frequency"])

In [142]:
freqTable["Age_unique_values"]=Dataset["Age"].value_counts().index
freqTable["Frequency"]=Dataset["Age"].value_counts().values
freqTable

    Age_unique_values  Frequency
0               28.00        202
1               24.00         30
2               22.00         27
3               18.00         26
4               19.00         25
..                ...        ...
83              36.50          1
84              55.50          1
85               0.92          1
86              23.50          1
87              74.00          1

[88 rows x 2 columns]

In [143]:
#Passenger class frequency
freqTable1=pd.DataFrame(columns=["Passengerclasses","Frequency"])
freqTable1["Passengerclasses"]=Dataset["Pclass"].value_counts().index
freqTable1["Frequency"]=Dataset["Pclass"].value_counts().values
freqTable1

   Passengerclasses  Frequency
0                 3        491
1                 1        216
2                 2        184

In [144]:
#Gender frequency
freqTable2=pd.DataFrame(columns=["Gender_values","Frequency"])
freqTable2["Gender_values"]=Dataset["Sex_male"].value_counts().index
freqTable2["Frequency"]=Dataset["Sex_male"].value_counts().values
freqTable2

   Gender_values  Frequency
0              1        577
1              0        314

In [146]:
lesser = []
greater = []

for columnName in ['Age','Fare']:
    if Dataset[columnName].min() < dupdata.loc["Lesser", columnName]:
        lesser.append(columnName)
    if Dataset[columnName].max() > dupdata.loc["Greater", columnName]:
        greater.append(columnName)

In [115]:
lesser

['Age']

In [116]:
greater

['Age']

In [147]:
Dataset_original = Dataset.copy()

In [148]:
for columnName in lesser:
    Dataset.loc[Dataset[columnName] < dupdata.loc["Lesser", columnName], columnName] = dupdata.loc["Lesser", columnName]

for columnName in greater:
    Dataset.loc[Dataset[columnName] > dupdata.loc["Greater", columnName], columnName] = dupdata.loc["Greater", columnName]

In [149]:
dupdata.loc["Min", columnName] = Dataset_original[columnName].min()
dupdata.loc["Max", columnName] = Dataset_original[columnName].max()

In [150]:
dupdata=pd.DataFrame(index=["mean","median","mode","Q1:25%","Q2:50%","Q3:75%","99","Q4:100%","IQR","1.5rule","Lesser","Greater","Min","Max"],columns=['Age','Fare'])
for columnName in ['Age','Fare']:
        dupdata.loc["mean", columnName]   = Dataset[columnName].mean()
        dupdata.loc["median", columnName] = Dataset[columnName].median()
        dupdata.loc["mode", columnName]   = Dataset[columnName].mode()[0]
        dupdata.loc["Q1:25%", columnName] = Dataset[columnName].quantile(0.25)
        dupdata.loc["Q2:50%", columnName] = Dataset[columnName].quantile(0.50)
        dupdata.loc["Q3:75%", columnName] = Dataset[columnName].quantile(0.75)
        dupdata.loc["99", columnName]     = np.percentile(Dataset[columnName], 99)
        dupdata.loc["Q4:100%", columnName]= Dataset[columnName].max()
        dupdata.loc["IQR", columnName]    = dupdata.loc["Q3:75%", columnName] - dupdata.loc["Q1:25%", columnName]
        dupdata.loc["1.5rule", columnName]= 1.5 * dupdata.loc["IQR", columnName]
        dupdata.loc["Lesser", columnName] = dupdata.loc["Q1:25%", columnName] - dupdata.loc["1.5rule", columnName]
        dupdata.loc["Greater", columnName]= dupdata.loc["Q3:75%", columnName] + dupdata.loc["1.5rule", columnName]
        dupdata.loc["Min", columnName]    = Dataset[columnName].min()
        dupdata.loc["Max", columnName]    = Dataset[columnName].max()

In [151]:
dupdata

               Age       Fare
mean     29.039282  24.046813
median        28.0    14.4542
mode          28.0    65.6344
Q1:25%        22.0     7.9104
Q2:50%        28.0    14.4542
Q3:75%        35.0       31.0
99            54.5    65.6344
Q4:100%       54.5    65.6344
IQR           13.0    23.0896
1.5rule       19.5    34.6344
Lesser         2.5    -26.724
Greater       54.5    65.6344
Min            2.5        0.0
Max           54.5    65.6344